{% set name = "iperf" %}
{% set version = "3.19.1" %}
{% set sha256 = "85e480d7fffdcb1368888aaee9d76bcfc211e17c2a6dcb2060b281498f82c97b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/esnet/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:

test:
  commands:
    - iperf3 --help

about:
  home: http://software.es.net/iperf/
  license: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: A TCP, UDP, and SCTP network bandwidth measurement tool

  doc_url: http://software.es.net/iperf/
  dev_url: https://github.com/esnet/iperf/

extra:
  recipe-maintainers:
    - brainstorm
