{% set name = "iperf" %}
{% set version = "3.5" %}
{% set sha256 = "4c318707a29d46d7b64e517a4fe5e5e75e698aef030c6906e9b26dc51d9b1fce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/esnet/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script: ./configure --prefix="${PREFIX}" && make && make install

requirements:
  build:
    - toolchain 

test:
  command:
    - iperf --help

about:
  home: https://iperf.fr 
  license: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'A TCP, UDP, and SCTP network bandwidth measurement tool'

  doc_url: https://iperf.fr/iperf-doc.php
  dev_url: https://github.com/esnet/iperf/

extra:
  recipe-maintainers:
    - brainstorm 
