appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: VsTwKuCIi7r+CUaXPs5A0v8KHa191JIZwMGn97nFT9d148cyW4yCNs0r0v40vH8mNg8DdtLipRAjxvo9Qc6QNsVk+gy9UlwxS0py+tYVSRdhVyUbm8dLMAYpX2qcZ/UwhQqhIxMchGgd4Z/LIaLR7nrSjIM/mM51f9J3818ZrMH/YU7GyUUaigCSQEn761hw0Tn7GcQPPW49yYA13q94eRD6GV4D8Wj6nsiXDFXkaov5qpabjoqKtqpHk8Z0ecEztCeDbYseSlSo6upR5hzVqtJTcq/ImUT3dB65KsBHALq7Xen2CJENjUUCJygY7pYgNcCDPO/sSHLOIiAULiKTKtDvf7hESVNc3uOeO+7EzT2loLFRNIY/heomSErqS6wpleA+YiwyY5dEEYCYCSGNPJHnv9QRTJZHmFBBRZ/63F5cig+cl1CnUAJ0RVP6rcKO3nB6D5bamcAwBlXkV6W1474hvzmJ/ikkxs+2p8sAAcsL9Bl31gXG5hzob4UvFruJe9s15EbL+IHVO9Dr38X++z0YX3aDS9AmIjCfP2F/RBLdK7tx9eizgBE7ZTqHmZUwS1RROnSeIVfLDqmJyn+PHyn6QSZpAluFOgZjHNweY4MbZu91yj91TNwWChtmqU55kplmPW4JuIqqrL7xOiFTVvfjpwbYRbVzWw1O4oP53WA=}
conda_forge_output_validation: true
bot:
  automerge: true
